"""empty message

Revision ID: 4115b95c666d
Revises: 4b6311b3e213
Create Date: 2014-08-20 15:48:45.320000

"""

# revision identifiers, used by Alembic.
revision = '4115b95c666d'
down_revision = '4b6311b3e213'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.add_column('article', sa.Column('like', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'like')
    op.create_table('user',
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('join_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('email'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
