"""empty message

Revision ID: 4b6311b3e213
Revises: d7740cb21e9
Create Date: 2014-08-18 18:29:49.887000

"""

# revision identifiers, used by Alembic.
revision = '4b6311b3e213'
down_revision = 'd7740cb21e9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.drop_column(u'article', 'like')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'article', sa.Column('like', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_table('user')
    ### end Alembic commands ###
